# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3808af7627385c685eed889d52489d4f4d6206e07d91d510849b068c44a813cbc16685bdb83ff22346277515dee223a1d89dc2aa396e90fc382a12f4b4b8555c

test:
  secret_key_base: 17da635628a95eb4b025ce5c3d0414da68072c4d5ee51cbf5219993df5d409f54a084d5899e94f33a9959c9ae350aa949c3d88b29ab38249316407cde3c2a2a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
